name: Translation Platform Server CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: yarn install
    
    - name: Run Build
      run: yarn build
      
    - name: Generate dotenv file
      run: |
        touch .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        echo PORT=3000 >> .env
        echo STT_SERVER_PORT=5050 >> .env
        echo ENV=prod >> .env
        echo JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }} >> .env
        echo ACCESS_TOKEN_EXPIRATION_TIME=900 >> .env
        echo REFRESH_TOKEN_EXPIRATION_TIME=1209600 >> .env
        cat .env
    
    - name: Create symbolic path to static folder
      run: ln -s ${{ secrets.PUBLIC_FOLDER_PATH }} dist/public
