name: Translation Platform Server CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: yarn install
    
    - name: Run Build
      run: yarn build
      
    - name: Generate dotenv file
      run: |
        touch dist/.env
        echo DB_URL=${{ secrets.DB_URL }} >> dist/.env
        echo PORT=3030 >> dist/.env
        echo ENV=prod >> dist/.env
        echo JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }} >> dist/.env
        echo ACCESS_TOKEN_EXPIRATION_TIME=900 >> dist/.env
        echo REFRESH_TOKEN_EXPIRATION_TIME=1209600 >> dist/.env
        cat dist/.env
